service: research-serverless-typeorm

useDotenv: true

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  # environment:
  #   JWT_SECRET: ${env:JWT_SECRET}
  #   HASH: ${env:DANNERCHANT}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /
          cors:
            headers: '*'

      - http:
          method: any
          path: /{proxy+}
          cors:
            headers: '*'

